# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/guso133/Documents/Neon-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/guso133/Documents/Neon-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guso133/Documents/Neon-Engine/CMakeFiles /Users/guso133/Documents/Neon-Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guso133/Documents/Neon-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f Dependencies/glfw/src/CMakeFiles/glfw.dir/build.make Dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

Dependencies/glad/src/glad.o: Dependencies/glad/src/glad.c.o

.PHONY : Dependencies/glad/src/glad.o

# target to build an object file
Dependencies/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.o
.PHONY : Dependencies/glad/src/glad.c.o

Dependencies/glad/src/glad.i: Dependencies/glad/src/glad.c.i

.PHONY : Dependencies/glad/src/glad.i

# target to preprocess a source file
Dependencies/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.i
.PHONY : Dependencies/glad/src/glad.c.i

Dependencies/glad/src/glad.s: Dependencies/glad/src/glad.c.s

.PHONY : Dependencies/glad/src/glad.s

# target to generate assembly for a file
Dependencies/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.s
.PHONY : Dependencies/glad/src/glad.c.s

NeonEngine/src/app/window.o: NeonEngine/src/app/window.cpp.o

.PHONY : NeonEngine/src/app/window.o

# target to build an object file
NeonEngine/src/app/window.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.o
.PHONY : NeonEngine/src/app/window.cpp.o

NeonEngine/src/app/window.i: NeonEngine/src/app/window.cpp.i

.PHONY : NeonEngine/src/app/window.i

# target to preprocess a source file
NeonEngine/src/app/window.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.i
.PHONY : NeonEngine/src/app/window.cpp.i

NeonEngine/src/app/window.s: NeonEngine/src/app/window.cpp.s

.PHONY : NeonEngine/src/app/window.s

# target to generate assembly for a file
NeonEngine/src/app/window.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.s
.PHONY : NeonEngine/src/app/window.cpp.s

NeonEngine/src/graphics/buffers/indexBuffer.o: NeonEngine/src/graphics/buffers/indexBuffer.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.o

# target to build an object file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.o

NeonEngine/src/graphics/buffers/indexBuffer.i: NeonEngine/src/graphics/buffers/indexBuffer.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.i

NeonEngine/src/graphics/buffers/indexBuffer.s: NeonEngine/src/graphics/buffers/indexBuffer.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.s

NeonEngine/src/graphics/buffers/vertexArray.o: NeonEngine/src/graphics/buffers/vertexArray.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.o

# target to build an object file
NeonEngine/src/graphics/buffers/vertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.o

NeonEngine/src/graphics/buffers/vertexArray.i: NeonEngine/src/graphics/buffers/vertexArray.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/vertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.i

NeonEngine/src/graphics/buffers/vertexArray.s: NeonEngine/src/graphics/buffers/vertexArray.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/vertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.s

NeonEngine/src/graphics/buffers/vertexBuffer.o: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.o

# target to build an object file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o

NeonEngine/src/graphics/buffers/vertexBuffer.i: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i

NeonEngine/src/graphics/buffers/vertexBuffer.s: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s

NeonEngine/src/graphics/cameras/camera.o: NeonEngine/src/graphics/cameras/camera.cpp.o

.PHONY : NeonEngine/src/graphics/cameras/camera.o

# target to build an object file
NeonEngine/src/graphics/cameras/camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.o
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.o

NeonEngine/src/graphics/cameras/camera.i: NeonEngine/src/graphics/cameras/camera.cpp.i

.PHONY : NeonEngine/src/graphics/cameras/camera.i

# target to preprocess a source file
NeonEngine/src/graphics/cameras/camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.i
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.i

NeonEngine/src/graphics/cameras/camera.s: NeonEngine/src/graphics/cameras/camera.cpp.s

.PHONY : NeonEngine/src/graphics/cameras/camera.s

# target to generate assembly for a file
NeonEngine/src/graphics/cameras/camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.s
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.s

NeonEngine/src/graphics/entities/gameobject.o: NeonEngine/src/graphics/entities/gameobject.cpp.o

.PHONY : NeonEngine/src/graphics/entities/gameobject.o

# target to build an object file
NeonEngine/src/graphics/entities/gameobject.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.o
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.o

NeonEngine/src/graphics/entities/gameobject.i: NeonEngine/src/graphics/entities/gameobject.cpp.i

.PHONY : NeonEngine/src/graphics/entities/gameobject.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/gameobject.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.i
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.i

NeonEngine/src/graphics/entities/gameobject.s: NeonEngine/src/graphics/entities/gameobject.cpp.s

.PHONY : NeonEngine/src/graphics/entities/gameobject.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/gameobject.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.s
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.s

NeonEngine/src/graphics/entities/mesh.o: NeonEngine/src/graphics/entities/mesh.cpp.o

.PHONY : NeonEngine/src/graphics/entities/mesh.o

# target to build an object file
NeonEngine/src/graphics/entities/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.o
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.o

NeonEngine/src/graphics/entities/mesh.i: NeonEngine/src/graphics/entities/mesh.cpp.i

.PHONY : NeonEngine/src/graphics/entities/mesh.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.i
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.i

NeonEngine/src/graphics/entities/mesh.s: NeonEngine/src/graphics/entities/mesh.cpp.s

.PHONY : NeonEngine/src/graphics/entities/mesh.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.s
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.s

NeonEngine/src/graphics/entities/model.o: NeonEngine/src/graphics/entities/model.cpp.o

.PHONY : NeonEngine/src/graphics/entities/model.o

# target to build an object file
NeonEngine/src/graphics/entities/model.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.o
.PHONY : NeonEngine/src/graphics/entities/model.cpp.o

NeonEngine/src/graphics/entities/model.i: NeonEngine/src/graphics/entities/model.cpp.i

.PHONY : NeonEngine/src/graphics/entities/model.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/model.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.i
.PHONY : NeonEngine/src/graphics/entities/model.cpp.i

NeonEngine/src/graphics/entities/model.s: NeonEngine/src/graphics/entities/model.cpp.s

.PHONY : NeonEngine/src/graphics/entities/model.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/model.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.s
.PHONY : NeonEngine/src/graphics/entities/model.cpp.s

NeonEngine/src/graphics/entities/renderable3d.o: NeonEngine/src/graphics/entities/renderable3d.cpp.o

.PHONY : NeonEngine/src/graphics/entities/renderable3d.o

# target to build an object file
NeonEngine/src/graphics/entities/renderable3d.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.o
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.o

NeonEngine/src/graphics/entities/renderable3d.i: NeonEngine/src/graphics/entities/renderable3d.cpp.i

.PHONY : NeonEngine/src/graphics/entities/renderable3d.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/renderable3d.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.i
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.i

NeonEngine/src/graphics/entities/renderable3d.s: NeonEngine/src/graphics/entities/renderable3d.cpp.s

.PHONY : NeonEngine/src/graphics/entities/renderable3d.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/renderable3d.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.s
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.s

NeonEngine/src/graphics/entities/renderableCollection.o: NeonEngine/src/graphics/entities/renderableCollection.cpp.o

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.o

# target to build an object file
NeonEngine/src/graphics/entities/renderableCollection.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.o
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.o

NeonEngine/src/graphics/entities/renderableCollection.i: NeonEngine/src/graphics/entities/renderableCollection.cpp.i

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/renderableCollection.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.i
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.i

NeonEngine/src/graphics/entities/renderableCollection.s: NeonEngine/src/graphics/entities/renderableCollection.cpp.s

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/renderableCollection.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.s
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.s

NeonEngine/src/graphics/entities/transform.o: NeonEngine/src/graphics/entities/transform.cpp.o

.PHONY : NeonEngine/src/graphics/entities/transform.o

# target to build an object file
NeonEngine/src/graphics/entities/transform.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.o
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.o

NeonEngine/src/graphics/entities/transform.i: NeonEngine/src/graphics/entities/transform.cpp.i

.PHONY : NeonEngine/src/graphics/entities/transform.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/transform.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.i
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.i

NeonEngine/src/graphics/entities/transform.s: NeonEngine/src/graphics/entities/transform.cpp.s

.PHONY : NeonEngine/src/graphics/entities/transform.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/transform.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.s
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.s

NeonEngine/src/graphics/renderers/forwardRenderer.o: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.o

# target to build an object file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o

NeonEngine/src/graphics/renderers/forwardRenderer.i: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.i

# target to preprocess a source file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i

NeonEngine/src/graphics/renderers/forwardRenderer.s: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.s

# target to generate assembly for a file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s

NeonEngine/src/main.o: NeonEngine/src/main.cpp.o

.PHONY : NeonEngine/src/main.o

# target to build an object file
NeonEngine/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.o
.PHONY : NeonEngine/src/main.cpp.o

NeonEngine/src/main.i: NeonEngine/src/main.cpp.i

.PHONY : NeonEngine/src/main.i

# target to preprocess a source file
NeonEngine/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.i
.PHONY : NeonEngine/src/main.cpp.i

NeonEngine/src/main.s: NeonEngine/src/main.cpp.s

.PHONY : NeonEngine/src/main.s

# target to generate assembly for a file
NeonEngine/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.s
.PHONY : NeonEngine/src/main.cpp.s

NeonEngine/src/shaders/program.o: NeonEngine/src/shaders/program.cpp.o

.PHONY : NeonEngine/src/shaders/program.o

# target to build an object file
NeonEngine/src/shaders/program.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.o
.PHONY : NeonEngine/src/shaders/program.cpp.o

NeonEngine/src/shaders/program.i: NeonEngine/src/shaders/program.cpp.i

.PHONY : NeonEngine/src/shaders/program.i

# target to preprocess a source file
NeonEngine/src/shaders/program.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.i
.PHONY : NeonEngine/src/shaders/program.cpp.i

NeonEngine/src/shaders/program.s: NeonEngine/src/shaders/program.cpp.s

.PHONY : NeonEngine/src/shaders/program.s

# target to generate assembly for a file
NeonEngine/src/shaders/program.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.s
.PHONY : NeonEngine/src/shaders/program.cpp.s

NeonEngine/src/shaders/shader.o: NeonEngine/src/shaders/shader.cpp.o

.PHONY : NeonEngine/src/shaders/shader.o

# target to build an object file
NeonEngine/src/shaders/shader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.o
.PHONY : NeonEngine/src/shaders/shader.cpp.o

NeonEngine/src/shaders/shader.i: NeonEngine/src/shaders/shader.cpp.i

.PHONY : NeonEngine/src/shaders/shader.i

# target to preprocess a source file
NeonEngine/src/shaders/shader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.i
.PHONY : NeonEngine/src/shaders/shader.cpp.i

NeonEngine/src/shaders/shader.s: NeonEngine/src/shaders/shader.cpp.s

.PHONY : NeonEngine/src/shaders/shader.s

# target to generate assembly for a file
NeonEngine/src/shaders/shader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.s
.PHONY : NeonEngine/src/shaders/shader.cpp.s

NeonEngine/src/shaders/texture.o: NeonEngine/src/shaders/texture.cpp.o

.PHONY : NeonEngine/src/shaders/texture.o

# target to build an object file
NeonEngine/src/shaders/texture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.o
.PHONY : NeonEngine/src/shaders/texture.cpp.o

NeonEngine/src/shaders/texture.i: NeonEngine/src/shaders/texture.cpp.i

.PHONY : NeonEngine/src/shaders/texture.i

# target to preprocess a source file
NeonEngine/src/shaders/texture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.i
.PHONY : NeonEngine/src/shaders/texture.cpp.i

NeonEngine/src/shaders/texture.s: NeonEngine/src/shaders/texture.cpp.s

.PHONY : NeonEngine/src/shaders/texture.s

# target to generate assembly for a file
NeonEngine/src/shaders/texture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.s
.PHONY : NeonEngine/src/shaders/texture.cpp.s

NeonEngine/src/utils/file_utils/fileUtils.o: NeonEngine/src/utils/file_utils/fileUtils.cpp.o

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.o

# target to build an object file
NeonEngine/src/utils/file_utils/fileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.o
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.o

NeonEngine/src/utils/file_utils/fileUtils.i: NeonEngine/src/utils/file_utils/fileUtils.cpp.i

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.i

# target to preprocess a source file
NeonEngine/src/utils/file_utils/fileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.i
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.i

NeonEngine/src/utils/file_utils/fileUtils.s: NeonEngine/src/utils/file_utils/fileUtils.cpp.s

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.s

# target to generate assembly for a file
NeonEngine/src/utils/file_utils/fileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.s
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.s

NeonEngine/src/utils/obj_loader/objloader.o: NeonEngine/src/utils/obj_loader/objloader.cpp.o

.PHONY : NeonEngine/src/utils/obj_loader/objloader.o

# target to build an object file
NeonEngine/src/utils/obj_loader/objloader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.o
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.o

NeonEngine/src/utils/obj_loader/objloader.i: NeonEngine/src/utils/obj_loader/objloader.cpp.i

.PHONY : NeonEngine/src/utils/obj_loader/objloader.i

# target to preprocess a source file
NeonEngine/src/utils/obj_loader/objloader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.i
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.i

NeonEngine/src/utils/obj_loader/objloader.s: NeonEngine/src/utils/obj_loader/objloader.cpp.s

.PHONY : NeonEngine/src/utils/obj_loader/objloader.s

# target to generate assembly for a file
NeonEngine/src/utils/obj_loader/objloader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.s
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... glad"
	@echo "... main"
	@echo "... glfw"
	@echo "... Dependencies/glad/src/glad.o"
	@echo "... Dependencies/glad/src/glad.i"
	@echo "... Dependencies/glad/src/glad.s"
	@echo "... NeonEngine/src/app/window.o"
	@echo "... NeonEngine/src/app/window.i"
	@echo "... NeonEngine/src/app/window.s"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.o"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.i"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.s"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.o"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.i"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.s"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.o"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.i"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.s"
	@echo "... NeonEngine/src/graphics/cameras/camera.o"
	@echo "... NeonEngine/src/graphics/cameras/camera.i"
	@echo "... NeonEngine/src/graphics/cameras/camera.s"
	@echo "... NeonEngine/src/graphics/entities/gameobject.o"
	@echo "... NeonEngine/src/graphics/entities/gameobject.i"
	@echo "... NeonEngine/src/graphics/entities/gameobject.s"
	@echo "... NeonEngine/src/graphics/entities/mesh.o"
	@echo "... NeonEngine/src/graphics/entities/mesh.i"
	@echo "... NeonEngine/src/graphics/entities/mesh.s"
	@echo "... NeonEngine/src/graphics/entities/model.o"
	@echo "... NeonEngine/src/graphics/entities/model.i"
	@echo "... NeonEngine/src/graphics/entities/model.s"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.o"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.i"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.s"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.o"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.i"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.s"
	@echo "... NeonEngine/src/graphics/entities/transform.o"
	@echo "... NeonEngine/src/graphics/entities/transform.i"
	@echo "... NeonEngine/src/graphics/entities/transform.s"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.o"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.i"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.s"
	@echo "... NeonEngine/src/main.o"
	@echo "... NeonEngine/src/main.i"
	@echo "... NeonEngine/src/main.s"
	@echo "... NeonEngine/src/shaders/program.o"
	@echo "... NeonEngine/src/shaders/program.i"
	@echo "... NeonEngine/src/shaders/program.s"
	@echo "... NeonEngine/src/shaders/shader.o"
	@echo "... NeonEngine/src/shaders/shader.i"
	@echo "... NeonEngine/src/shaders/shader.s"
	@echo "... NeonEngine/src/shaders/texture.o"
	@echo "... NeonEngine/src/shaders/texture.i"
	@echo "... NeonEngine/src/shaders/texture.s"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.o"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.i"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.s"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.o"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.i"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

