# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aroberd/Documents/Neon-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aroberd/Documents/Neon-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-bin\" \"assimp-dev\" \"libassimp4.1.0\" \"libassimp4.1.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aroberd/Documents/Neon-Engine/CMakeFiles /Users/aroberd/Documents/Neon-Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aroberd/Documents/Neon-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/CMakeFiles/uninstall.dir/build.make Dependencies/assimp-4.1.0/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make Dependencies/assimp-4.1.0/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/code/CMakeFiles/assimp.dir/build.make Dependencies/assimp-4.1.0/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named assimp_cmd

# Build rule for target.
assimp_cmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp_cmd
.PHONY : assimp_cmd

# fast build rule for target.
assimp_cmd/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make Dependencies/assimp-4.1.0/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build
.PHONY : assimp_cmd/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/unit.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/unit.dir/build
.PHONY : unit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousCoverage.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousTest.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousBuild.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousStart.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalBuild.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalCoverage.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalSubmit.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousUpdate.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalUpdate.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalStart.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousSubmit.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalTest.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlySubmit.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyMemCheck.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalConfigure.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyCoverage.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyTest.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousMemCheck.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyBuild.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyConfigure.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyUpdate.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyMemoryCheck.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousConfigure.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/Nightly.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyStart.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalMemCheck.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/Continuous.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f Dependencies/assimp-4.1.0/test/CMakeFiles/Experimental.dir/build.make Dependencies/assimp-4.1.0/test/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f Dependencies/glfw/src/CMakeFiles/glfw.dir/build.make Dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

Dependencies/glad/src/glad.o: Dependencies/glad/src/glad.c.o

.PHONY : Dependencies/glad/src/glad.o

# target to build an object file
Dependencies/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.o
.PHONY : Dependencies/glad/src/glad.c.o

Dependencies/glad/src/glad.i: Dependencies/glad/src/glad.c.i

.PHONY : Dependencies/glad/src/glad.i

# target to preprocess a source file
Dependencies/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.i
.PHONY : Dependencies/glad/src/glad.c.i

Dependencies/glad/src/glad.s: Dependencies/glad/src/glad.c.s

.PHONY : Dependencies/glad/src/glad.s

# target to generate assembly for a file
Dependencies/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/Dependencies/glad/src/glad.c.s
.PHONY : Dependencies/glad/src/glad.c.s

NeonEngine/src/app/window.o: NeonEngine/src/app/window.cpp.o

.PHONY : NeonEngine/src/app/window.o

# target to build an object file
NeonEngine/src/app/window.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.o
.PHONY : NeonEngine/src/app/window.cpp.o

NeonEngine/src/app/window.i: NeonEngine/src/app/window.cpp.i

.PHONY : NeonEngine/src/app/window.i

# target to preprocess a source file
NeonEngine/src/app/window.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.i
.PHONY : NeonEngine/src/app/window.cpp.i

NeonEngine/src/app/window.s: NeonEngine/src/app/window.cpp.s

.PHONY : NeonEngine/src/app/window.s

# target to generate assembly for a file
NeonEngine/src/app/window.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/app/window.cpp.s
.PHONY : NeonEngine/src/app/window.cpp.s

NeonEngine/src/graphics/buffers/indexBuffer.o: NeonEngine/src/graphics/buffers/indexBuffer.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.o

# target to build an object file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.o

NeonEngine/src/graphics/buffers/indexBuffer.i: NeonEngine/src/graphics/buffers/indexBuffer.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.i

NeonEngine/src/graphics/buffers/indexBuffer.s: NeonEngine/src/graphics/buffers/indexBuffer.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/indexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/indexBuffer.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/indexBuffer.cpp.s

NeonEngine/src/graphics/buffers/vertexArray.o: NeonEngine/src/graphics/buffers/vertexArray.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.o

# target to build an object file
NeonEngine/src/graphics/buffers/vertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.o

NeonEngine/src/graphics/buffers/vertexArray.i: NeonEngine/src/graphics/buffers/vertexArray.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/vertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.i

NeonEngine/src/graphics/buffers/vertexArray.s: NeonEngine/src/graphics/buffers/vertexArray.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/vertexArray.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/vertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexArray.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/vertexArray.cpp.s

NeonEngine/src/graphics/buffers/vertexBuffer.o: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.o

# target to build an object file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.o

NeonEngine/src/graphics/buffers/vertexBuffer.i: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.i

# target to preprocess a source file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.i

NeonEngine/src/graphics/buffers/vertexBuffer.s: NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s

.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.s

# target to generate assembly for a file
NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s
.PHONY : NeonEngine/src/graphics/buffers/vertexBuffer.cpp.s

NeonEngine/src/graphics/cameras/camera.o: NeonEngine/src/graphics/cameras/camera.cpp.o

.PHONY : NeonEngine/src/graphics/cameras/camera.o

# target to build an object file
NeonEngine/src/graphics/cameras/camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.o
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.o

NeonEngine/src/graphics/cameras/camera.i: NeonEngine/src/graphics/cameras/camera.cpp.i

.PHONY : NeonEngine/src/graphics/cameras/camera.i

# target to preprocess a source file
NeonEngine/src/graphics/cameras/camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.i
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.i

NeonEngine/src/graphics/cameras/camera.s: NeonEngine/src/graphics/cameras/camera.cpp.s

.PHONY : NeonEngine/src/graphics/cameras/camera.s

# target to generate assembly for a file
NeonEngine/src/graphics/cameras/camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/cameras/camera.cpp.s
.PHONY : NeonEngine/src/graphics/cameras/camera.cpp.s

NeonEngine/src/graphics/entities/gameobject.o: NeonEngine/src/graphics/entities/gameobject.cpp.o

.PHONY : NeonEngine/src/graphics/entities/gameobject.o

# target to build an object file
NeonEngine/src/graphics/entities/gameobject.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.o
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.o

NeonEngine/src/graphics/entities/gameobject.i: NeonEngine/src/graphics/entities/gameobject.cpp.i

.PHONY : NeonEngine/src/graphics/entities/gameobject.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/gameobject.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.i
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.i

NeonEngine/src/graphics/entities/gameobject.s: NeonEngine/src/graphics/entities/gameobject.cpp.s

.PHONY : NeonEngine/src/graphics/entities/gameobject.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/gameobject.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/gameobject.cpp.s
.PHONY : NeonEngine/src/graphics/entities/gameobject.cpp.s

NeonEngine/src/graphics/entities/mesh.o: NeonEngine/src/graphics/entities/mesh.cpp.o

.PHONY : NeonEngine/src/graphics/entities/mesh.o

# target to build an object file
NeonEngine/src/graphics/entities/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.o
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.o

NeonEngine/src/graphics/entities/mesh.i: NeonEngine/src/graphics/entities/mesh.cpp.i

.PHONY : NeonEngine/src/graphics/entities/mesh.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.i
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.i

NeonEngine/src/graphics/entities/mesh.s: NeonEngine/src/graphics/entities/mesh.cpp.s

.PHONY : NeonEngine/src/graphics/entities/mesh.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/mesh.cpp.s
.PHONY : NeonEngine/src/graphics/entities/mesh.cpp.s

NeonEngine/src/graphics/entities/model.o: NeonEngine/src/graphics/entities/model.cpp.o

.PHONY : NeonEngine/src/graphics/entities/model.o

# target to build an object file
NeonEngine/src/graphics/entities/model.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.o
.PHONY : NeonEngine/src/graphics/entities/model.cpp.o

NeonEngine/src/graphics/entities/model.i: NeonEngine/src/graphics/entities/model.cpp.i

.PHONY : NeonEngine/src/graphics/entities/model.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/model.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.i
.PHONY : NeonEngine/src/graphics/entities/model.cpp.i

NeonEngine/src/graphics/entities/model.s: NeonEngine/src/graphics/entities/model.cpp.s

.PHONY : NeonEngine/src/graphics/entities/model.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/model.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/model.cpp.s
.PHONY : NeonEngine/src/graphics/entities/model.cpp.s

NeonEngine/src/graphics/entities/renderable3d.o: NeonEngine/src/graphics/entities/renderable3d.cpp.o

.PHONY : NeonEngine/src/graphics/entities/renderable3d.o

# target to build an object file
NeonEngine/src/graphics/entities/renderable3d.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.o
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.o

NeonEngine/src/graphics/entities/renderable3d.i: NeonEngine/src/graphics/entities/renderable3d.cpp.i

.PHONY : NeonEngine/src/graphics/entities/renderable3d.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/renderable3d.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.i
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.i

NeonEngine/src/graphics/entities/renderable3d.s: NeonEngine/src/graphics/entities/renderable3d.cpp.s

.PHONY : NeonEngine/src/graphics/entities/renderable3d.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/renderable3d.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderable3d.cpp.s
.PHONY : NeonEngine/src/graphics/entities/renderable3d.cpp.s

NeonEngine/src/graphics/entities/renderableCollection.o: NeonEngine/src/graphics/entities/renderableCollection.cpp.o

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.o

# target to build an object file
NeonEngine/src/graphics/entities/renderableCollection.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.o
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.o

NeonEngine/src/graphics/entities/renderableCollection.i: NeonEngine/src/graphics/entities/renderableCollection.cpp.i

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/renderableCollection.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.i
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.i

NeonEngine/src/graphics/entities/renderableCollection.s: NeonEngine/src/graphics/entities/renderableCollection.cpp.s

.PHONY : NeonEngine/src/graphics/entities/renderableCollection.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/renderableCollection.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/renderableCollection.cpp.s
.PHONY : NeonEngine/src/graphics/entities/renderableCollection.cpp.s

NeonEngine/src/graphics/entities/transform.o: NeonEngine/src/graphics/entities/transform.cpp.o

.PHONY : NeonEngine/src/graphics/entities/transform.o

# target to build an object file
NeonEngine/src/graphics/entities/transform.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.o
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.o

NeonEngine/src/graphics/entities/transform.i: NeonEngine/src/graphics/entities/transform.cpp.i

.PHONY : NeonEngine/src/graphics/entities/transform.i

# target to preprocess a source file
NeonEngine/src/graphics/entities/transform.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.i
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.i

NeonEngine/src/graphics/entities/transform.s: NeonEngine/src/graphics/entities/transform.cpp.s

.PHONY : NeonEngine/src/graphics/entities/transform.s

# target to generate assembly for a file
NeonEngine/src/graphics/entities/transform.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/entities/transform.cpp.s
.PHONY : NeonEngine/src/graphics/entities/transform.cpp.s

NeonEngine/src/graphics/renderers/forwardRenderer.o: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.o

# target to build an object file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.o

NeonEngine/src/graphics/renderers/forwardRenderer.i: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.i

# target to preprocess a source file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.i

NeonEngine/src/graphics/renderers/forwardRenderer.s: NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s

.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.s

# target to generate assembly for a file
NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s
.PHONY : NeonEngine/src/graphics/renderers/forwardRenderer.cpp.s

NeonEngine/src/main.o: NeonEngine/src/main.cpp.o

.PHONY : NeonEngine/src/main.o

# target to build an object file
NeonEngine/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.o
.PHONY : NeonEngine/src/main.cpp.o

NeonEngine/src/main.i: NeonEngine/src/main.cpp.i

.PHONY : NeonEngine/src/main.i

# target to preprocess a source file
NeonEngine/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.i
.PHONY : NeonEngine/src/main.cpp.i

NeonEngine/src/main.s: NeonEngine/src/main.cpp.s

.PHONY : NeonEngine/src/main.s

# target to generate assembly for a file
NeonEngine/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/main.cpp.s
.PHONY : NeonEngine/src/main.cpp.s

NeonEngine/src/shaders/program.o: NeonEngine/src/shaders/program.cpp.o

.PHONY : NeonEngine/src/shaders/program.o

# target to build an object file
NeonEngine/src/shaders/program.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.o
.PHONY : NeonEngine/src/shaders/program.cpp.o

NeonEngine/src/shaders/program.i: NeonEngine/src/shaders/program.cpp.i

.PHONY : NeonEngine/src/shaders/program.i

# target to preprocess a source file
NeonEngine/src/shaders/program.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.i
.PHONY : NeonEngine/src/shaders/program.cpp.i

NeonEngine/src/shaders/program.s: NeonEngine/src/shaders/program.cpp.s

.PHONY : NeonEngine/src/shaders/program.s

# target to generate assembly for a file
NeonEngine/src/shaders/program.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/program.cpp.s
.PHONY : NeonEngine/src/shaders/program.cpp.s

NeonEngine/src/shaders/shader.o: NeonEngine/src/shaders/shader.cpp.o

.PHONY : NeonEngine/src/shaders/shader.o

# target to build an object file
NeonEngine/src/shaders/shader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.o
.PHONY : NeonEngine/src/shaders/shader.cpp.o

NeonEngine/src/shaders/shader.i: NeonEngine/src/shaders/shader.cpp.i

.PHONY : NeonEngine/src/shaders/shader.i

# target to preprocess a source file
NeonEngine/src/shaders/shader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.i
.PHONY : NeonEngine/src/shaders/shader.cpp.i

NeonEngine/src/shaders/shader.s: NeonEngine/src/shaders/shader.cpp.s

.PHONY : NeonEngine/src/shaders/shader.s

# target to generate assembly for a file
NeonEngine/src/shaders/shader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/shader.cpp.s
.PHONY : NeonEngine/src/shaders/shader.cpp.s

NeonEngine/src/shaders/texture.o: NeonEngine/src/shaders/texture.cpp.o

.PHONY : NeonEngine/src/shaders/texture.o

# target to build an object file
NeonEngine/src/shaders/texture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.o
.PHONY : NeonEngine/src/shaders/texture.cpp.o

NeonEngine/src/shaders/texture.i: NeonEngine/src/shaders/texture.cpp.i

.PHONY : NeonEngine/src/shaders/texture.i

# target to preprocess a source file
NeonEngine/src/shaders/texture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.i
.PHONY : NeonEngine/src/shaders/texture.cpp.i

NeonEngine/src/shaders/texture.s: NeonEngine/src/shaders/texture.cpp.s

.PHONY : NeonEngine/src/shaders/texture.s

# target to generate assembly for a file
NeonEngine/src/shaders/texture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/shaders/texture.cpp.s
.PHONY : NeonEngine/src/shaders/texture.cpp.s

NeonEngine/src/utils/file_utils/fileUtils.o: NeonEngine/src/utils/file_utils/fileUtils.cpp.o

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.o

# target to build an object file
NeonEngine/src/utils/file_utils/fileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.o
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.o

NeonEngine/src/utils/file_utils/fileUtils.i: NeonEngine/src/utils/file_utils/fileUtils.cpp.i

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.i

# target to preprocess a source file
NeonEngine/src/utils/file_utils/fileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.i
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.i

NeonEngine/src/utils/file_utils/fileUtils.s: NeonEngine/src/utils/file_utils/fileUtils.cpp.s

.PHONY : NeonEngine/src/utils/file_utils/fileUtils.s

# target to generate assembly for a file
NeonEngine/src/utils/file_utils/fileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/file_utils/fileUtils.cpp.s
.PHONY : NeonEngine/src/utils/file_utils/fileUtils.cpp.s

NeonEngine/src/utils/obj_loader/objloader.o: NeonEngine/src/utils/obj_loader/objloader.cpp.o

.PHONY : NeonEngine/src/utils/obj_loader/objloader.o

# target to build an object file
NeonEngine/src/utils/obj_loader/objloader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.o
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.o

NeonEngine/src/utils/obj_loader/objloader.i: NeonEngine/src/utils/obj_loader/objloader.cpp.i

.PHONY : NeonEngine/src/utils/obj_loader/objloader.i

# target to preprocess a source file
NeonEngine/src/utils/obj_loader/objloader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.i
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.i

NeonEngine/src/utils/obj_loader/objloader.s: NeonEngine/src/utils/obj_loader/objloader.cpp.s

.PHONY : NeonEngine/src/utils/obj_loader/objloader.s

# target to generate assembly for a file
NeonEngine/src/utils/obj_loader/objloader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NeonEngine/src/utils/obj_loader/objloader.cpp.s
.PHONY : NeonEngine/src/utils/obj_loader/objloader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install"
	@echo "... glad"
	@echo "... list_install_components"
	@echo "... main"
	@echo "... uninstall"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... assimp_cmd"
	@echo "... unit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... NightlyMemoryCheck"
	@echo "... ContinuousConfigure"
	@echo "... Nightly"
	@echo "... NightlyStart"
	@echo "... ExperimentalMemCheck"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... glfw"
	@echo "... Dependencies/glad/src/glad.o"
	@echo "... Dependencies/glad/src/glad.i"
	@echo "... Dependencies/glad/src/glad.s"
	@echo "... NeonEngine/src/app/window.o"
	@echo "... NeonEngine/src/app/window.i"
	@echo "... NeonEngine/src/app/window.s"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.o"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.i"
	@echo "... NeonEngine/src/graphics/buffers/indexBuffer.s"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.o"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.i"
	@echo "... NeonEngine/src/graphics/buffers/vertexArray.s"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.o"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.i"
	@echo "... NeonEngine/src/graphics/buffers/vertexBuffer.s"
	@echo "... NeonEngine/src/graphics/cameras/camera.o"
	@echo "... NeonEngine/src/graphics/cameras/camera.i"
	@echo "... NeonEngine/src/graphics/cameras/camera.s"
	@echo "... NeonEngine/src/graphics/entities/gameobject.o"
	@echo "... NeonEngine/src/graphics/entities/gameobject.i"
	@echo "... NeonEngine/src/graphics/entities/gameobject.s"
	@echo "... NeonEngine/src/graphics/entities/mesh.o"
	@echo "... NeonEngine/src/graphics/entities/mesh.i"
	@echo "... NeonEngine/src/graphics/entities/mesh.s"
	@echo "... NeonEngine/src/graphics/entities/model.o"
	@echo "... NeonEngine/src/graphics/entities/model.i"
	@echo "... NeonEngine/src/graphics/entities/model.s"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.o"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.i"
	@echo "... NeonEngine/src/graphics/entities/renderable3d.s"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.o"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.i"
	@echo "... NeonEngine/src/graphics/entities/renderableCollection.s"
	@echo "... NeonEngine/src/graphics/entities/transform.o"
	@echo "... NeonEngine/src/graphics/entities/transform.i"
	@echo "... NeonEngine/src/graphics/entities/transform.s"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.o"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.i"
	@echo "... NeonEngine/src/graphics/renderers/forwardRenderer.s"
	@echo "... NeonEngine/src/main.o"
	@echo "... NeonEngine/src/main.i"
	@echo "... NeonEngine/src/main.s"
	@echo "... NeonEngine/src/shaders/program.o"
	@echo "... NeonEngine/src/shaders/program.i"
	@echo "... NeonEngine/src/shaders/program.s"
	@echo "... NeonEngine/src/shaders/shader.o"
	@echo "... NeonEngine/src/shaders/shader.i"
	@echo "... NeonEngine/src/shaders/shader.s"
	@echo "... NeonEngine/src/shaders/texture.o"
	@echo "... NeonEngine/src/shaders/texture.i"
	@echo "... NeonEngine/src/shaders/texture.s"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.o"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.i"
	@echo "... NeonEngine/src/utils/file_utils/fileUtils.s"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.o"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.i"
	@echo "... NeonEngine/src/utils/obj_loader/objloader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

